//ANSWERS
//Question 1

let firstName = 'Ruqayah'
console.log(firstName);
 
let secondName = "Abdulkareem"
console.log(secondName);
let country = 'Nigeria'
console.log(country);
let city=`Ilorin`
console.log(city);
let age = '31'
console.log(age);
let year = "2024"
console.log(year);
let isMarried = 'No'
console.log(isMarried);


console.log(typeof 'Ruqayah')
console.log(typeof secondName);

console.log(typeof country)
console.log(typeof Ilorin);
console.log(typeof city);
console.log(typeof age);
console.log(typeof 31);
console.log(typeof year);
console.log(typeof 2024);
console.log(typeof No);
console.log(typeof false);
console.log(typeof isMarried);

//Question 2
console.log(10==10)
console.log(10===10);
console.log(10==10);
console.log(9.8==10);
console.log(9.8==10);

let isLightOn = true
let isLightoff = !isLightOn
let isTravel=!false

let tru='An equalsign in javascript is an assignment operator'
console.log(tru);

let tuu = 'arithmetric operators are mathematical operator'
console.log(tuu);
 let tryth= 'boolean value is either true or false'
 console.log(tryth);


/*undefined value
boolean are numbers 
the empty strings*/


console.log(4>3);
console.log(4>=3);
console.log(4<3);
console.log(4==4);
console.log(4===4);
console.log(4!=4)
console.log(4!==4);
console.log(4=='4');
console.log(4==='4');
//lenght of python and jargon
console.log('python'.length == 'jargon'.length);
console.log('python'.length === 'jargon'.length);
console.log('python'.length != 'jargon'.length);
console.log('python'.length !=='jargon'.length);
console.log('python'.length > 'jargon'.length);
console.log('python'.length < 'jargon'.length);


 console.log(4>3&& 10<12);
console.log (4>3&& 10>12);
console.log(4>3|| 10<12);
console.log (4>3|| 10>12);























/*const now = new Date()
console.log(now.getFullYear());

const wor = new Date()
console.log(wor.getMonth());

const dot = new Date()
console.log(dot.getDay());

const wit = new Date()
console.log(wit.getHours());*/
